version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./build:/srv/jekyll
    #working_dir: /build
    #environment:
      #JEKYLL_UID: 1001
      #JEKYLL_GID: 1001