apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsf-design-system
  labels:
    app: dsf-design-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsf-design-system
  template:
    metadata:
      labels:
        app: dsf-design-system
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dsf-design-system
        image: ghcr.io/gov-cy/dsf-design-system:main
        imagePullPolicy: Always
        ports:
          - containerPort: 80
