apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsf-design-system-k8s-temp
  labels:
    app: dsf-design-system-k8s-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsf-design-system-k8s-temp
  template:
    metadata:
      labels:
        app: dsf-design-system-k8s-temp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dsf-design-system-k8s-temp
        image: ghcr.io/gov-cy/dsf-design-system-k8s-temp:main
        imagePullPolicy: Always
        ports:
          - containerPort: 80
